In [1]:
# Lista funcionam como vetores e matrizes, dinâmico e qualquer tipo de dados

In [30]:
#1Elaborar um algoritmo que lê um conjunto de 30 valores e os coloca em 2 vetores conforme forem pares ou
#ímpares. O tamanho do vetor é de 5 posições. Terminada a leitura escrever o conteúdo dos dois vetores. Cada
#vetor pode ser preenchido tantas vezes quantas for necessário.

vet1 = np.random.randint(1,100, (1,30)) 

In [3]:
#2Escreva um algoritmo que leia dois vetores de 10 posições e faça a multiplicação dos elementos de mesmo
#índice, colocando o resultado em um terceiro vetor. Mostre o vetor resultante.
import random
import numpy as np
vet1 = np.random.randint(1,20, (1,10)) 
vet2 = np.random.randint(1,20, (1,10)) 
print(vet1)
print(vet2)
print(vet1 * vet2)

[[19  3  7 18  3  1  1  6  2 12]]
[[ 5 19 13  8 19 10  8  6  5  5]]
[[ 95  57  91 144  57  10   8  36  10  60]]


In [4]:
#3Escreva um algoritmo que leia e mostre um vetor de 20 elementos inteiros. a seguir, conte quantos valores
#pares existem no vetor.

vet1 = np.random.randint(1,100, (1,20)) 
print(vet1)
print('A quantidade de pares é : {}'.format(np.count_nonzero(vet1 % 2 == 1))) 


[[11 32 63 87  2 74  6 71 57  8 81 26 21 61 16 34 45 83 16 30]]
A quantidade de pares é : 10


In [5]:
#4 Escreva um algoritmo que leia um vetor de 10 posições e mostre-o ordenado em ordem crescente utilizando o 
#método BubleSort. Escreva a quantidade de comparações que foram realizadas
import numpy as np
def bubble_sort(vetor):
  n = len(vetor)

  for i in range(n):
    for j in range(0, n - i - 1):
      if vetor[j] > vetor[j + 1]:
        temp = vetor[j]
        vetor[j] = vetor[j + 1]
        vetor[j + 1] = temp
  return vetor   

bubble_sort(np.array([95,74,1,8,10,25,5,41,13,45]))

array([ 1,  5,  8, 10, 13, 25, 41, 45, 74, 95])

In [6]:
#5 Escreva um algoritmo que leia um vetor de 10 posições e mostre-o ordenado em ordem crescente utilizando o 
#método SelectionSort. Escreva a quantidade de comparações que foram realizadas.
def selection_sort(vetor):
  n = len(vetor)

  for i in range(n):
    id_minimo = i
    for j in range(i + 1, n):
      if vetor[id_minimo] > vetor[j]:
        id_minimo = j
    temp = vetor[i]
    vetor[i] = vetor[id_minimo]
    vetor[id_minimo] = temp
  
  return vetor

selection_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#6Escreva um algoritmo que leia um vetor de 10 posições e mostre- o. Em seguida, troque o primeiro elemento 
#com o último, o segundo com o penúltimo, o terceiro com o antepenúltimo, e assim sucessivamente. Mostre o 
#novo vetor depois da troca.

In [36]:
#7Escreva um algoritmo que leia um vetor de 10 posições de números inteiros e mostre somente os positivos. 
vet1 = [1,-5,3,-1,-6,4,-2,-10,-7,-8]
[ x for x in vet1 if x < 0]   #ListComprehention

[-5, -1, -6, -2, -10, -7, -8]

In [32]:
#8Escreva um algoritmo que leia um vetor de 80 elementos inteiros. Encontre e mostre o menor elemento e sua 
#posição no vetor.
vet1 = np.random.randint(1,100, (1,80)) 
print(vet1)
np.min(vet1)



[[74 42  1 36 14 31 40 78 84 41  9 85 32 39 59 69 16 97 77 10 58 69 21 85
  28  2 10 13 92 18 77  8  1 69 92 24 78 91 37 24 48 58 32 70  3 84 84 33
  64 68 97 91 82 93 41 68 10 50 80  4 67 70 98 20 19 31 90 67 50 20 39 73
  99 95 72 97  9 60 23 71]]


1

In [48]:
#9Escrever um algoritmo que lê 2 vetores de tamanho 10 e os escreve. Crie, a seguir, um vetor de 20 posições 
#que contenha os elementos dos outros 2 vetores em ordem crescente. 









In [47]:
vet1 = np.random.randint(1,100, (1,10)) ; vet1
vet2 = np.random.randint(1,100, (1,10)) ;
vet3 = np.concatenate((vet1, vet2)) ;vet3

array([[95, 85, 17, 12,  2, 79, 60, 31,  5, 44],
       [99, 36, 31, 17, 85, 75, 73,  8, 51, 10]])

In [25]:
#c Soma
x = np.random.randint(1,30, (1,10)) 
y = np.random.randint(1,30, (1,10)) 

z = x + y
print(x)
print(y)
print(z)

[[18 24 24  3 22 20 15  7 24  9]]
[[21 28 14  1  3 26 11 29  6 18]]
[[39 52 38  4 25 46 26 36 30 27]]


In [26]:
#d Produto
z = x * y
print(x)
print(y)
print(z)

[[18 24 24  3 22 20 15  7 24  9]]
[[21 28 14  1  3 26 11 29  6 18]]
[[378 672 336   3  66 520 165 203 144 162]]


In [28]:
#e Interseção
z = np.intersect1d(x,y)
print(x)
print(y)
print(z)

[[18 24 24  3 22 20 15  7 24  9]]
[[21 28 14  1  3 26 11 29  6 18]]
[ 3 18]


In [29]:
z = np.union1d(x, y)
print(x)
print(y)
print(z)

[[18 24 24  3 22 20 15  7 24  9]]
[[21 28 14  1  3 26 11 29  6 18]]
[ 1  3  6  7  9 11 14 15 18 20 21 22 24 26 28 29]


In [ ]:
#11Escrever um algoritmo que lê um vetor X(20) e o escreve. Escreva, a seguir, cada um dos valores distintos 
#que aparecem em X dizendo quantas vezes cada valor aparece em X. 

In [35]:
m = np.matrix('1,1,1,1,1,1; 1,2,2,2,2,1 ; 1,2,3,3,2,1 ; 1,2,3,3,2,1 ; 1,2,2,2,2,1 ; 1,1,1,1,1,1')
m


matrix([[1, 1, 1, 1, 1, 1],
        [1, 2, 2, 2, 2, 1],
        [1, 2, 3, 3, 2, 1],
        [1, 2, 3, 3, 2, 1],
        [1, 2, 2, 2, 2, 1],
        [1, 1, 1, 1, 1, 1]])