## Lista de Exercícios 02_ Vetores, Matrizes e Ordenação

In [2]:
import random
import numpy as np
vet1 = np.random.randint(1,20, (1,10)) 
vet2 = np.random.randint(1,20, (1,10)) 
print(vet1)
print(vet2)
print(vet1 * vet2)

[[17 16 18 14  7 19  6  6  2 19]]
[[16  8 19 12 15  8  7 17 17 10]]
[[272 128 342 168 105 152  42 102  34 190]]


In [3]:
vet1 = np.random.randint(1,100, (1,20)) 
print(vet1)
print('A quantidade de pares é : {}'.format(np.count_nonzero(vet1 % 2 == 1))) 

[[88 79 66  6 69 54 55 15 81 22 10  6 68 52 63 54 17 80  8 86]]
A quantidade de pares é : 7


In [4]:
import numpy as np
def bubble_sort(vetor):
  n = len(vetor)

  for i in range(n):
    for j in range(0, n - i - 1):
      if vetor[j] > vetor[j + 1]:
        temp = vetor[j]
        vetor[j] = vetor[j + 1]
        vetor[j + 1] = temp
  return vetor   

bubble_sort(np.array([95,74,1,8,10,25,5,41,13,45]))

array([ 1,  5,  8, 10, 13, 25, 41, 45, 74, 95])

In [5]:
def selection_sort(vetor):
  n = len(vetor)

  for i in range(n):
    id_minimo = i
    for j in range(i + 1, n):
      if vetor[id_minimo] > vetor[j]:
        id_minimo = j
    temp = vetor[i]
    vetor[i] = vetor[id_minimo]
    vetor[id_minimo] = temp
  
  return vetor

selection_sort(np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1]))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
vet1 = [1,-5,3,-1,-6,4,-2,-10,-7,-8]
[ x for x in vet1 if x < 0]   #ListComprehention

[-5, -1, -6, -2, -10, -7, -8]

In [8]:
vet1 = np.random.randint(10,100, (1,80)) 
print(vet1)
np.min(vet1)


[[33 23 95 32 27 44 48 61 57 32 58 82 68 34 44 47 78 54 52 88 89 80 14 85
  50 96 76 67 64 81 74 77 83 16 72 50 37 17 56 84 93 18 53 58 34 14 65 86
  50 76 68 67 34 87 60 23 41 91 85 88 68 65 55 95 34 69 51 28 77 40 20 77
  71 79 21 84 66 12 66 62]]


12

In [10]:
# a) a união de X com Y
x = np.random.randint(1,30, (1,10)) 
y = np.random.randint(1,30, (1,10))
z = np.union1d(x, y)
print(x)
print(y)
print(z)

[[24 26 16 11 13 18  2  8 27  3]]
[[23 27 13  8 24  4 12 29 12 21]]
[ 2  3  4  8 11 12 13 16 18 21 23 24 26 27 29]


In [13]:
# b) a diferença entre X e Y
z = x - y
z

array([[  1,  -1,   3,   3, -11,  14, -10, -21,  15, -18]])

In [14]:
# c) a Soma entre X e Y
z = x + y
z

array([[47, 53, 29, 19, 37, 22, 14, 37, 39, 24]])

In [16]:
# d)O produto entre X e Y
z = x * y
z

array([[552, 702, 208,  88, 312,  72,  24, 232, 324,  63]])

In [17]:
# e) A intersecção entre x e y
z = np.intersect1d(x,y)
print(x)
print(y)
print(z)

[[24 26 16 11 13 18  2  8 27  3]]
[[23 27 13  8 24  4 12 29 12 21]]
[ 8 13 24 27]


In [18]:
m = np.matrix('1,1,1,1,1,1; 1,2,2,2,2,1 ; 1,2,3,3,2,1 ; 1,2,3,3,2,1 ; 1,2,2,2,2,1 ; 1,1,1,1,1,1')
m

matrix([[1, 1, 1, 1, 1, 1],
        [1, 2, 2, 2, 2, 1],
        [1, 2, 3, 3, 2, 1],
        [1, 2, 3, 3, 2, 1],
        [1, 2, 2, 2, 2, 1],
        [1, 1, 1, 1, 1, 1]])